# JAFS Configuration File

model:
  provider: ollama
  model_name: qwq:32b
  base_url: "http://localhost:11434"  # Default Ollama API URL
  temperature: 0.7

agent:
  name: jafs
  mode: auto  # Changed from multi to auto
  max_iterations: 10
  memory_capacity: 2000
  verbose: true

tools:
  enabled:
    - calculator
    - search
    - text
    - code

logging:
  level: DEBUG
  file: logs/jafs.log
